# -*- coding: utf-8 -*-
"""micrograd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qroG8eFz44nQkYWjvoiPjw25ubAjfyNG
"""

# Commented out IPython magic to ensure Python compatibility.
import math
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline

def f(x):
    return 3*x**2 - 4*x +5

f(3.0)

xs = np.arange(-5, 5, 0.25)
xs

ys = f(xs)
ys

plt.plot(xs,ys)

h = 0.001
x = 3
f(x+h)

(f(x+h)-f(x))/h

a = 2.0
b = -3.0
c = 10.0
d = a*b + c
print("Original value of d: ", d)

h = 0.001
a += h
d1 = a*b + c
print("Value of d when a changes slightly: ", d1)
print("Derivative of d with respect to a: ", (d1-d)/h)
a -= h

b+= h
d2 = a*b + c
print("Value of d when b changes slightly: ", d2)
print("Derivative of d with respect to b: ", (d2-d)/h)
b -= h

c+=h
d3 = a*b + c
print("Value of d when c changes slightly: ", d3)
print("Derivative of d with respect to c: ", (d3-d)/h)

class Value:
    def __init__(self,data, _children = (), _op='', label =''):
        self.data = data
        self.grad = 0.0
        self._backward = lambda: None
        self._prev = set(_children)
        self._op = _op
        self.label = label

    def __repr__(self):
        return f"Value(data={self.data})"

    def __add__(self,other):
        other = other if isinstance(other, Value) else Value(other)
        out = Value(self.data + other.data, (self,other), '+')
        def _backward():
            self.grad += 1.0 * out.grad
            other.grad += 1.0 * out.grad
        out._backward = _backward
        return out

    def __mul__(self,other):
        other = other if isinstance(other, Value) else Value(other)
        out = Value(self.data * other.data, (self,other), '*')
        def _backward():
            self.grad += other.data * out.grad
            other.grad += self.data * out.grad
        out._backward = _backward
        return out

    def __pow__(self, other):
        assert isinstance(other, (int, float))
        out = Value(self.data ** other, (self, ), f'**{other}')
        def _backward():
            self.grad += other * (self.data ** (other -1)) * out.grad
        out._backward = _backward
        return out

    def __radd__(self, other):
        return self + other

    def __rmul__(self, other):
        return self * other

    def __truediv__(self, other):
        return self * other ** -1

    def __neg__(self):
        return self * -1

    def __sub__(self, other):
        return self + (-other)

    def tanh(self):
        x = self.data
        t = (math.exp(2*x)-1)/(math.exp(2*x)+1)
        out = Value(t, (self, ), 'tanh')
        def _backward():
            self.grad += (1 - t**2) * out.grad
        out._backward = _backward
        return out

    def exp(self):
        x = self.data
        out = Value(math.exp(x), (self, ), 'exp')
        def _backward():
            self.grad += out.data * out.grad
        out._backward = _backward
        return out

    def backward(self):
        topo = []
        visited = set()
        def build_topo(v):
            if v not in visited:
                visited.add(v)
                for child in v._prev:
                    build_topo(child)
                topo.append(v)
        build_topo(self)
        self.grad = 1.0
        for node in reversed(topo):
            node._backward()

a = Value(2.0)
b = Value(4.0)
a - b

from graphviz import Digraph
def trace(root):
    nodes, edges = set(), set()
    def build(v):
        if v not in nodes:
            nodes.add(v)
            for child in v._prev:
                edges.add((child, v))
                build(child)
    build(root)
    return nodes, edges

def draw_dot(root):
    dot = Digraph(format = 'svg', graph_attr={'rankdir':'LR'})
    nodes, edges = trace(root)
    for n in nodes:
        uid = str(id(n))
        dot.node(name = uid, label = "{ %s | data %.4f | grad %.4f }" % (n.label,n.data,n.grad), shape = 'record')
        if n._op:
            dot.node(name = uid + n._op, label = n._op)
            dot.edge(uid + n._op, uid)
    for n1, n2 in edges:
        dot.edge(str(id(n1)), str(id(n2)) + n2._op)
    return dot

# inputs
x1 = Value(2.0, label = 'x1')
x2 = Value(0.0, label = 'x2')
# weights
w1 = Value(-3.0, label = 'w1')
w2 = Value(1.0, label = 'w2')
#bias
b = Value(6.8813735870195432, label = 'b')
# x1w1 + x2w2 + b
x1w1 = x1*w1; x1w1.label = 'x1*w1'
x2w2 = x2*w2; x2w2.label = 'x2*w2'
x1w1x2w2 = x1w1 + x2w2; x1w1x2w2.label = 'x1*w1 + x2*w2'
n = x1w1x2w2 + b; n.label = 'n'
o = n.tanh(); o.label = 'o'
o.backward()

draw_dot(o)

# inputs
x1 = Value(2.0, label = 'x1')
x2 = Value(0.0, label = 'x2')
# weights
w1 = Value(-3.0, label = 'w1')
w2 = Value(1.0, label = 'w2')
#bias
b = Value(6.8813735870195432, label = 'b')
# x1w1 + x2w2 + b
x1w1 = x1*w1; x1w1.label = 'x1*w1'
x2w2 = x2*w2; x2w2.label = 'x2*w2'
x1w1x2w2 = x1w1 + x2w2; x1w1x2w2.label = 'x1*w1 + x2*w2'
n = x1w1x2w2 + b; n.label = 'n'
# ---
e = (2*n).exp()
o = (e - 1) / (e + 1)
# ---
o.label = 'o'
o.backward()
draw_dot(o)

o.backward()

a = Value(-2.0, label = 'a')
b = Value(3.0, label = 'b')
d = a * b; d.label = 'd'
e = a + b; e.label = 'e'
f = d * e; f.label = 'f'
f.backward()
draw_dot(f)

import torch

x1 = torch.Tensor([2.0]).double(); x1.requires_grad = True
x2 = torch.Tensor([0.0]).double(); x2.requires_grad = True
w1 = torch.Tensor([-3.0]).double(); w1.requires_grad = True
w2 = torch.Tensor([1.0]).double(); w2.requires_grad = True
b = torch.Tensor([6.8813735870195432]).double(); b.requires_grad = True
n = x1*w1 + x2*w2 + b
o = torch.tanh(n)

print(o.data.item())
o.backward()

print('---')
print('x2', x2.grad.item())
print('w2', w2.grad.item())
print('x1', x1.grad.item())
print('w1', w1.grad.item())

x2.grad.item()

import random
class Neuron:
    def __init__(self, nin):
        self.w = [Value(random.uniform(-1,1)) for _ in range(nin)]
        self.b = Value(random.uniform(-1,1))

    def __call__(self, x):
        act = sum((wi*xi for wi, xi in zip(self.w, x)), self.b)
        out = act.tanh()
        return out

    def parameters(self):
        return self.w + [self.b]

class Layer:
    def __init__(self, nin, nout):
        self.neurons = [Neuron(nin) for _ in range(nout)]

    def __call__(self, x):
        outs = [n(x) for n in self.neurons]
        return outs[0] if len(outs) == 1 else outs

    def parameters(self):
        return [p for neuron in self.neurons for p in neuron.parameters()] # Returns parameters of the layer

# nout in number of neurons in a single layer while nouts is the lists of layers
class MLP:
    def __init__(self, nin, nouts):
        sz = [nin] + nouts # nouts = [4,20,100] defines a NN with 3 layers with 4 neurons in the first layer, 20 in the 2nd and 100 in the 3rd
        self.layers = [Layer(sz[i], sz[i+1]) for i in range(len(nouts))] # [Layer(sz[i], sz[i+1]) for i in range(len(nouts))] iterates over the indices of the nouts list.
        # For each index i, a new Layer is created with sz[i] as the number of inputs (nin) and sz[i+1] as the number of neurons (nout) in that layer

    def __call__(self, x):
        for layer in self.layers:
            x = layer(x) # The output of previous layer is the input of the next layer
        return x

    def parameters(self):
        return [p for layer in self.layers for p in layer.parameters()]

x = [2.0, 3.0, -1.0]
n = MLP(3, [4,4,1]) # 3 is nin and the list is nouts
n(x)

n.parameters()

draw_dot(n(x))

xs = [
    [2.0, 3.0, -1.0, 4.0, 2.5, 8.1, 3.7],
    [3.0, -1.0, 0.5, 8.1, -1.0, 3.0, 4.5],
    [0.5, 1.0, 1.0, 5.0, -11.0, 2.5, 1.1],
    [1.0, 1.0, -1.0, -2.5, -4.3, 7.4, 1.0],
    [1.0, 3.3, 4.0, 4.0, 22.0, -4.9, 5.1]
] # Output of this NN is yout
ys = [1.0, -1.0, -1.0, 1.0, 1.0] # desired tagrets (ygt)
ypred = [n(x) for x in xs]
ypred

loss = sum((yout - ygt)**2 for ygt, yout in zip(ys, ypred))
loss

loss.backward()

n.layers[0].neurons[0].w[0].grad

n.layers[0].neurons[0].w[0].data # value of weight

# Negative gradient has implies inverse influence on the loss, so slightly increasing this weight of this neuron of this layer will make the loss go down

draw_dot(loss)

for p in n.parameters():
    p.data += -0.01 * p.grad # gradient is -ve so multipying with -0.01 will increase the will
# We want to increase the value of the weight as increasing it will make the loss go down, think of gradient as pointing
# in the direction of inreasing loss, here the gradient is -ve so reducing the value will increase the loss, we want to
# reduce the loss

ypred = [n(x) for x in xs]
loss = sum((yout - ygt)**2 for ygt, yout in zip(ys, ypred)) # forward pass with adjusted weights
loss
# re-calculating loss after adjusting parameters according to their gradient

# Loss went down

# Repeating back propogation with adjusted weights and again tuning them

loss.backward() # backward pass with adjusted weights

for p in n.parameters():
    p.data += -0.01 * p.grad # repeat
ypred = [n(x) for x in xs]
loss = sum((yout - ygt)**2 for ygt, yout in zip(ys, ypred))
loss

# Reduced again, this is bascially gradient descent - forward pass with adjusted weights then backward pass with adjusted weights and repeat until loss keeps decreasing

ypred

# With very low loss the predictions are basically perfect

n.parameters()

for k in range(50):
     # forward pass
    ypred = [n(x) for x in xs]
    loss = sum((yout-ygt)**2 for ygt, yout in zip(ys, ypred))

    # backward pass
    for p in n.parameters():
        p.grad = 0.0 # resetting gradients of all weights to zero for every iteration (forgot in prevous run)
    loss.backward()

    # update
    for p in n.parameters():
        p.data += -0.1 * p.grad

    print(k, loss.data)

ypred

# Even closer predictions

